# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v1
        with: 
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: publish
        run: npm publish --access public
        env: 
            NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
          
